name = "FLEXECOM"
uuid = "8d7f05c3-7c9a-4f18-b67a-3e6e4944e9fc"
authors = ["√Ålvaro Manso Burgos <almanbur@upv.es>"]
version = "1.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
Gurobi_jll = "c018c7e6-a5b0-4aea-8f80-9c1ef9991411"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[compat]
CSV = "0.10"
DataFrames = "1.0"
Distributions = "0.25"
Gurobi = "1.0"
Gurobi_jll = "12.0.3"
JLD2 = "0.4"
JuMP = "1.0"
MAT = "0.10"
Plots = "1.0"
StatsPlots = "0.15"
XLSX = "0.9"
julia = "1.8"
